/* Auto-generated from 'Digitide Group Facility Tracker As on 1 Sep 2026 (For Internal Circulation)'.
   Field-for-field from the tracker; nothing edited except whitespace. Regenerate via
   scratchpad gen_fac.py against a newer tracker rather than hand-editing rows. */
window.DG_FACILITIES = [
  {
    "sr": 1,
    "region": "North",
    "state": "New Delhi",
    "location": "Delhi",
    "facility": "Delhi",
    "address": "Plot-17, 3rd Floor, West Patel Nagar, New Delhi, 110008",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Collection Centre",
    "lessor": "Gurleen Kaur, Amit Bhasin, Ajit Singh Ajmani, Charanjeet Kaur , Harleen Kaur Ajmani & Harmeet Singh Ajmani",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2022-04-01",
    "leaseEnd": "2027-03-31",
    "city": "delhi"
  },
  {
    "sr": 2,
    "region": "North",
    "state": "Rajasthan",
    "location": "Jaipur",
    "facility": "Jaipur",
    "address": "Sankalp Tower,Office No. 215 & 216, 2nd Floor, Queens Road Turn, Khatipura Road, Jaipur-302021",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Collection Centre",
    "lessor": "Seema Kanwar Shekhawat",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2024-10-01",
    "leaseEnd": "2026-09-30",
    "city": "jaipur"
  },
  {
    "sr": 3,
    "region": "North",
    "state": "Punjab",
    "location": "Jalandhar",
    "facility": "Jalandhar",
    "address": "Niramal Complex,Ground Floor, E.H.198,G.T.Road ,Jalhandar (Pb.)144001",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Collection Centre",
    "lessor": "Gagandeep Singh, Prabhdeep Singh & Jaspal Singh",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2026-02-01",
    "leaseEnd": "2029-01-31",
    "city": "jalandhar"
  },
  {
    "sr": 4,
    "region": "North",
    "state": "Uttar Pradesh",
    "location": "Lucknow",
    "facility": "Summit Building 13th Floor",
    "address": "13th Floor, TCG 3/3, Wing-A & Wing-B Summit Building, Vibhuti Khand Gomti Nagar, Lucknow, UP-226010",
    "officeType": "Leased by Digitide & Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "Highness infra Developers Pvt. Ltd",
    "lessee": "Digitide Solutions Ltd",
    "leaseStart": "2026-04-01",
    "leaseEnd": "2029-03-31",
    "city": "lucknow"
  },
  {
    "sr": 5,
    "region": "North",
    "state": "Uttar Pradesh",
    "location": "Lucknow",
    "facility": "Lucknow",
    "address": "SKY HI Chambers,107,1st Floor, 5-Park Road, Hazratganj, Lucknow-226001",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Collection Centre",
    "lessor": "Shalini Singh",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2026-04-01",
    "leaseEnd": "2027-03-31",
    "city": "lucknow"
  },
  {
    "sr": 6,
    "region": "North",
    "state": "Punjab",
    "location": "Ludhiana",
    "facility": "Ludhiana",
    "address": "Madhok Complex, Gurdev Nagar, Ferozpur road, Ludhiana, 144001",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Collection Centre",
    "lessor": "Madhok Banquet",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2025-01-05",
    "leaseEnd": "2027-01-04",
    "city": "ludhiana"
  },
  {
    "sr": 7,
    "region": "North",
    "state": "Punjab",
    "location": "Mohali",
    "facility": "Competent House, C-157, SAS Nagar",
    "address": "Plot No C-157, Phase-7, Industrial Area SAS Nagar Mohali- 160055-Punjab, India",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "Sanjay Tandon",
    "lessee": "Digitide Solutions Ltd",
    "leaseStart": "2024-09-20",
    "leaseEnd": "2030-09-19",
    "city": "mohali"
  },
  {
    "sr": 8,
    "region": "North",
    "state": "Haryana",
    "location": "Hissar",
    "facility": "Hissar",
    "address": "Shop No 30, First Floor, Guru Jambeshwar Market, Parijat Chowk, Hissar Haryana-125001",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Collection Centre",
    "lessor": "Narain Dass",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2024-04-01",
    "leaseEnd": "2027-03-31",
    "city": "hissar"
  },
  {
    "sr": 9,
    "region": "North",
    "state": "Uttar Pradesh",
    "location": "Noida",
    "facility": "Sector-62",
    "address": "Dr. ITM, 4th Floor - C56A/10 & 11, Sector-62, Noida UP 201309",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "Dr. ITM Limited",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2026-05-01",
    "leaseEnd": "2027-03-31",
    "city": "noida"
  },
  {
    "sr": 10,
    "region": "North",
    "state": "Uttar Pradesh",
    "location": "Noida",
    "facility": "Sector-58",
    "address": "Industrial plot numbers A-94/5 and A-94/6, 2nd & 3rd Floor,Sector 58, Noida, UP 201301",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "EFC Limited",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2024-07-01",
    "leaseEnd": "2029-06-30",
    "city": "noida"
  },
  {
    "sr": 11,
    "region": "South",
    "state": "Karnataka",
    "location": "Bangalore",
    "facility": "Krimson Square",
    "address": "31/9, Krimson Square, 1st floor, Roopena Agrahara, Bangalore - 560068",
    "officeType": "Leased by Digitide & Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "Mr. K. Prasad Smt. Kavitha Prasad Smt. K Asha Smt. K Nagarathana Mr. Krishna Reddy Mr. Srinivasa Reddy",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2023-06-01",
    "leaseEnd": "2028-05-31",
    "city": "bangalore"
  },
  {
    "sr": 12,
    "region": "South",
    "state": "Karnataka",
    "location": "Bellary",
    "facility": "Bellary",
    "address": "2nd Floor, Chamber Building , K C Road Bellari-583101",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "Ballari Dist Chamber of Commerce & Ind",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2024-10-01",
    "leaseEnd": "2028-03-31",
    "city": "bellary"
  },
  {
    "sr": 13,
    "region": "South",
    "state": "Telengana",
    "location": "Secundrabad",
    "facility": "Ranigunj",
    "address": "EFC Ltd, 3rd Floor, Lalla-1 Landmark, MG Road, Ranigunj, Secundrabad",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "EFC Limited",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2026-02-01",
    "leaseEnd": "2029-01-31",
    "city": "hyderabad"
  },
  {
    "sr": 14,
    "region": "South",
    "state": "Telengana",
    "location": "Secundrabad",
    "facility": "Ranigunj",
    "address": "EFC Ltd, 4th Floor, Lalla-1 Landmark, MG Road, Ranigunj, Secundrabad",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "EFC Limited",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2026-02-01",
    "leaseEnd": "2029-01-31",
    "city": "hyderabad"
  },
  {
    "sr": 15,
    "region": "South",
    "state": "Telengana",
    "location": "Secundrabad",
    "facility": "Ranigunj",
    "address": "EFC Ltd, 6th Floor, Lalla-1 Landmark, MG Road, Ranigunj, Secundrabad",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "EFC Limited",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2026-02-01",
    "leaseEnd": "2029-01-31",
    "city": "hyderabad"
  },
  {
    "sr": 16,
    "region": "South",
    "state": "Telengana",
    "location": "Secundrabad",
    "facility": "Ranigunj",
    "address": "EFC Ltd, 5th Floor, Lalla-1 Landmark, MG Road, Ranigunj, Secundrabad",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "EFC Limited",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2022-04-01",
    "leaseEnd": "2027-03-31",
    "city": "hyderabad"
  },
  {
    "sr": 17,
    "region": "South",
    "state": "Telengana",
    "location": "Secundrabad",
    "facility": "Ranigunj",
    "address": "EFC Ltd, 5th Floor, Lalla-1 Landmark, MG Road, Ranigunj, Secundrabad",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "EFC Limited",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2023-12-15",
    "leaseEnd": "2028-12-14",
    "city": "hyderabad"
  },
  {
    "sr": 18,
    "region": "South",
    "state": "Telangana",
    "location": "Begumpet",
    "facility": "Begumpet",
    "address": "Gowra Trinity, S. P. Road, Patigadda, Begumpet, Hyderabad, Telangana 500049",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "Gowra Lakshmi Narayana Gowra Subbaram Gowra Subbaraj Gowra Nagarjun Gowra Aditya Vasavi Builders",
    "lessee": "Quess",
    "leaseStart": "2022-01-15",
    "leaseEnd": "2031-07-31",
    "city": "hyderabad"
  },
  {
    "sr": 19,
    "region": "South",
    "state": "Kerela",
    "location": "Munnar",
    "facility": "Munnar",
    "address": "1758A/IX, 1st Floor, SARA COTTAGE, MUNNAR, Idukki, Kerala, 685612,",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "M/s Sara Cottage",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2026-03-01",
    "leaseEnd": "2027-01-31",
    "city": "munnar"
  },
  {
    "sr": 20,
    "region": "South",
    "state": "Tamilnadu",
    "location": "Coimbatore",
    "facility": "Coimbatore",
    "address": "Manchester Square, No-14, Ground floor,Puliyakulam road,Opp kidney center,Coimbatore-641038",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "Mohamed Sadiq",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2025-04-01",
    "leaseEnd": "2028-09-30",
    "city": "coimbatore"
  },
  {
    "sr": 21,
    "region": "South",
    "state": "Tamilnadu",
    "location": "Coimbatore",
    "facility": "Coimbatore",
    "address": "Manchester square, No-2/1, 2nd floor, Puliyakulam Road,Opp kidneycenter, Coimbatore - 641037",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "Lakshmanan Murugappan",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2025-12-01",
    "leaseEnd": "2026-10-31",
    "city": "coimbatore"
  },
  {
    "sr": 22,
    "region": "South",
    "state": "Tamilnadu",
    "location": "Coimbatore",
    "facility": "Coimbatore",
    "address": "Manchester square, No-12/2, 2nd floor, Puliyakulam Road,Opp kidneycenter, Coimbatore - 641037",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "Mohamed Sadiq",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2025-04-01",
    "leaseEnd": "2027-12-31",
    "city": "coimbatore"
  },
  {
    "sr": 23,
    "region": "South",
    "state": "Tamil Nadu",
    "location": "Chennai",
    "facility": "RVI Tower",
    "address": "RVI Tower, 6th Floor, Velachery Tambaram Main Road, Pallikaranai, Chennai-600 100",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "RVI Reality LLP",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2024-11-15",
    "leaseEnd": "2029-11-14",
    "city": "chennai"
  },
  {
    "sr": 24,
    "region": "South",
    "state": "Tamil Nadu",
    "location": "Chennai",
    "facility": "RVI Tower",
    "address": "RVI Tower, 2nd Floor, Velachery Tambaram Main Road, Pallikaranai, Chennai-600 100",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "RVI Reality LLP",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2025-04-01",
    "leaseEnd": "2030-03-31",
    "city": "chennai"
  },
  {
    "sr": 25,
    "region": "South",
    "state": "Karnataka",
    "location": "Bangalore",
    "facility": "SS Plaza",
    "address": "SS Plaza, SS Plaza, 74, 27th Main, Old Madiwala, Jay Bheema Nagar, 1st Stage, BTM 1st Stage, Bengaluru, Karnataka 560068",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "Parsvatech Workspaces PVT. LTD",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2025-04-01",
    "leaseEnd": "2034-04-01",
    "city": "bangalore"
  },
  {
    "sr": 26,
    "region": "East",
    "state": "Jharkhand",
    "location": "Jamshedpur",
    "facility": "Jamshedpur",
    "address": "G.P.Slope, Gwalpara Primary School, Near Kadma Water Tank, Opposite To Kadma Police Station, Kadma, Jamshedpur-831005, Jharkhand, India",
    "officeType": "Leased",
    "centreType": "Call Centre",
    "lessor": "TATA Steel Limited",
    "lessee": "Quess",
    "leaseStart": "2023-01-28",
    "leaseEnd": "2028-11-15",
    "city": "jamshedpur"
  },
  {
    "sr": 27,
    "region": "East",
    "state": "West Bengal",
    "location": "Kolkata",
    "facility": "Technopolis",
    "address": "Tehcnopolis Building, 10th & 11th Floor, Street Number 1, BP Block, Sector V, BIdhanNagar, North 24,Parganas, Kolkata, West Bengal-700091",
    "officeType": "Managed Office",
    "centreType": "Call Centre",
    "lessor": "Awfis Space Solutions Limited",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2022-10-06",
    "leaseEnd": "2027-10-05",
    "city": "kolkata"
  },
  {
    "sr": 28,
    "region": "East",
    "state": "West Bengal",
    "location": "Kolkata",
    "facility": "Millennium City",
    "address": "Millennium City Tower 2, 10th Floor, 62 DN Block, Sector V, Bidhannagar, Kolkata West Bengal - 700091",
    "officeType": "Managed Office",
    "centreType": "Call Centre",
    "lessor": "EFC Ltd",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2025-06-06",
    "leaseEnd": "2030-06-05",
    "city": "kolkata"
  },
  {
    "sr": 29,
    "region": "East",
    "state": "Odisha",
    "location": "Bhubaneswar",
    "facility": "Bhubaneswar",
    "address": "Esplanade Mall , Room no. 427, Fourth floor, Safari, Cuttack Road, Rasulgarh Industrial Estate, Bhubaneswar, Khordha, Odisha 751010",
    "officeType": "Leased",
    "centreType": "Collection Centre",
    "lessor": "Subhrat Brahma",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2022-01-01",
    "leaseEnd": "2026-12-31",
    "city": "bhubaneswar"
  },
  {
    "sr": 30,
    "region": "East",
    "state": "Bihar",
    "location": "Patna",
    "facility": "Patna",
    "address": "Jagattarani Tower,204, Basudev Complex, Jamal Road, Patna - 800001",
    "officeType": "Leased",
    "centreType": "Collection Centre",
    "lessor": "Tribhuwan Bhagat",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2024-11-11",
    "leaseEnd": "2026-11-10",
    "city": "patna"
  },
  {
    "sr": 31,
    "region": "East",
    "state": "Assam",
    "location": "Guwahati",
    "facility": "Guwahati",
    "address": "Kalpana market, 2 Floor, Guwahati Club, near Bus stand Silpukhri, Guwahati- 781003, Assam",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Collection Centre",
    "lessor": "Omaya Spaces",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2025-12-04",
    "leaseEnd": "2026-12-02",
    "city": "guwahati"
  },
  {
    "sr": 32,
    "region": "West",
    "state": "Maharashtra",
    "location": "Navi Mumbai",
    "facility": "Airoli 1",
    "address": "Reliable Tech Park, Unit 102 & 103, 1st Floor, B Wing, Thane-Belapur Road, Airoli, Navi Mumbai - 400708, Maharashtra, India",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "Reliable Exports (India) Pvt Ltd",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2025-04-01",
    "leaseEnd": "2030-03-31",
    "city": "navimumbai"
  },
  {
    "sr": 33,
    "region": "West",
    "state": "Maharashtra",
    "location": "Navi Mumbai",
    "facility": "Airoli 3",
    "address": "Reliable Tech park, Unit 104, 1st floor, C wing, cloud city campus, Airoli Thane Belapur Road, Navi Mumbai – 400708, India.",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "EFC Limited",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2021-12-24",
    "leaseEnd": "2026-12-23",
    "city": "navimumbai"
  },
  {
    "sr": 34,
    "region": "West",
    "state": "Maharashtra",
    "location": "Navi Mumbai",
    "facility": "Airoli 4",
    "address": "Empire Tower, 10th Floor, Office No. 1001 & 1002, Plot No. K-10, MIDC, TTC Ind. Area, Airoli, Thane, Navi Mumbai - 400708, India",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "EFC Limited",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2022-05-19",
    "leaseEnd": "2027-05-18",
    "city": "navimumbai"
  },
  {
    "sr": 35,
    "region": "West",
    "state": "Maharashtra",
    "location": "Navi Mumbai",
    "facility": "Sigma IT Park, Rabale",
    "address": "Kanakia Sigma IT Park, 2nd floor, TTC Industrail Estate, Ghansoli Buhari Marg, Belapur Road, Sec-8, Rabale Navi Mumbai-400701",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "Parsvatech Workspaces PVT. LTD",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2023-05-12",
    "leaseEnd": "2028-05-11",
    "city": "navimumbai"
  },
  {
    "sr": 36,
    "region": "West",
    "state": "Maharashtra",
    "location": "Navi Mumbai",
    "facility": "Sigma IT Park, Rabale",
    "address": "Kanakia Sigma IT Park, 7th floor, TTC Industrail Estate, Ghansoli Buhari Marg, Belapur Road, Sec-8, Rabale Navi Mumbai-400701",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "Parsvatech Workspaces PVT. LTD",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2023-06-10",
    "leaseEnd": "2028-06-09",
    "city": "navimumbai"
  },
  {
    "sr": 37,
    "region": "West",
    "state": "Maharashtra",
    "location": "Thane",
    "facility": "Kasar",
    "address": "MBC Park, 4th Floor, C Building, Near Hypercity Mall, GB Road, Kasarwadavli, Thane - 400615, Maharashtra, India",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "Ankur Decor Pvt. Ltd. & Pratibha Agriware Pvt. Ltd.",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2025-10-01",
    "leaseEnd": "2030-09-30",
    "city": "thane"
  },
  {
    "sr": 38,
    "region": "West",
    "state": "Maharashtra",
    "location": "Thane",
    "facility": "Kasar",
    "address": "MBC Park, 8th Floor, C Building, Near Hypercity Mall, GB Road, Kasarwadavli, Thane - 400615, Maharashtra, India",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "JASP Enterprises LLP",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2022-05-15",
    "leaseEnd": "2027-05-14",
    "city": "thane"
  },
  {
    "sr": 39,
    "region": "West",
    "state": "Maharashtra",
    "location": "Thane",
    "facility": "Ashar IT Park",
    "address": "Ashar IT Park, Office no.B-3, 4th floor, B-wing Jayhsree Baugh, Road no.16Z, Wagle Industrial Estate, Thane, West, Maharashtra-400604",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "Shree Om Namah Infraprojects LLP",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2024-01-15",
    "leaseEnd": "2029-06-14",
    "city": "thane"
  },
  {
    "sr": 40,
    "region": "West",
    "state": "Maharashtra",
    "location": "Thane",
    "facility": "Kalpataru Prime",
    "address": "Kalpataru Prime, Unit No-2, 1st floor, Plot no D-3, Road no.16, MIDC, Wagle Industrail Estate, Thane (W)- 400604",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "KPSB Realtech LLP",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2023-05-08",
    "leaseEnd": "2028-05-07",
    "city": "thane"
  },
  {
    "sr": 41,
    "region": "West",
    "state": "Maharashtra",
    "location": "Borivali",
    "facility": "Borivali",
    "address": "Om Shreeji Darshan, Carter Rd. No-2 Dattapada, Near Muncipal Hospital , Borivali East",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Collection Centre",
    "lessor": "Pravin Lagad",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2023-12-05",
    "leaseEnd": "2026-12-04",
    "city": "mumbai"
  },
  {
    "sr": 42,
    "region": "West",
    "state": "Maharashtra",
    "location": "Thane",
    "facility": "Kolshet",
    "address": "ETPL Tower- 1st, 2nd, 3rd and 4th floor , Dhokali, Kolshet Road, Thane west- 400 604",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "Parsvatech Workspaces PVT. LTD",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2025-08-01",
    "leaseEnd": "2029-12-31",
    "city": "thane"
  },
  {
    "sr": 43,
    "region": "West",
    "state": "Maharashtra",
    "location": "Pune",
    "facility": "Devi IT",
    "address": "ICC Devi Gaurav Tech Park Building, 3Rd Floor, Sr.No. 191 To 195, Old Mumbai Pune Highway, Pimpri, Pune, Maharashtra – 411 018. Phone - 020 - 67138469",
    "officeType": "Owned",
    "centreType": "Call Centre",
    "lessor": "Digitide",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": null,
    "leaseEnd": null,
    "city": "pune"
  },
  {
    "sr": 44,
    "region": "West",
    "state": "Maharashtra",
    "location": "Pune",
    "facility": "Kharadi E Park",
    "address": "E-Park, 3Rd Floor,Plot No. 3/1, Kharadi Knowledge Park, Midc,Pune -411014, Maharashtra, India",
    "officeType": "Leased with Managed Office",
    "centreType": "Call Centre",
    "lessor": "EFC Ltd",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2025-06-01",
    "leaseEnd": "2028-05-31",
    "city": "pune"
  },
  {
    "sr": 45,
    "region": "West",
    "state": "Maharashtra",
    "location": "Pune",
    "facility": "Almonte",
    "address": "Office No-301, 3Rd Floor Almonte It Park Rakshak Nagar Kharadi, Pune - 411014",
    "officeType": "Leased with Managed Office",
    "centreType": "Call Centre",
    "lessor": "EFC Ltd",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2022-03-19",
    "leaseEnd": "2027-03-18",
    "city": "pune"
  },
  {
    "sr": 46,
    "region": "West",
    "state": "Gujarat",
    "location": "Mithapur",
    "facility": "Mithapur",
    "address": "C/O. Tata Chemicals Ltd, Mithapur – 361345, District - Jamnagar, Gujarat",
    "officeType": "Leased",
    "centreType": "Call Centre",
    "lessor": "Tata Chemicals Ltd",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2026-04-01",
    "leaseEnd": "2027-03-31",
    "city": "mithapur"
  },
  {
    "sr": 47,
    "region": "West",
    "state": "Maharashtra",
    "location": "Nagpur",
    "facility": "Nagpur",
    "address": "R.K.Business Centre ,2Nd Floor ,Plot No .194 , Cement Road , Dharampeth Extension ,Near Shivajinagar Nagpur-440010 , Ph.-0712-2523624",
    "officeType": "Managed Office",
    "centreType": "Collection Centre",
    "lessor": "R K BUSINESS CENTRE",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2026-06-01",
    "leaseEnd": "2027-05-31",
    "city": "nagpur"
  },
  {
    "sr": 48,
    "region": "West",
    "state": "Maharashtra",
    "location": "kolhapur",
    "facility": "kolhapur",
    "address": "1605 A Ward, Tarabai Raod, Near Maha E-Seva Kendra, Shivaji Peth, Kolhapur 416012.",
    "officeType": "Leased",
    "centreType": "Collection Centre",
    "lessor": "Vilas Bhongale",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2026-04-01",
    "leaseEnd": "2027-03-31",
    "city": "kolhapur"
  },
  {
    "sr": 49,
    "region": "West",
    "state": "Maharashtra",
    "location": "Srirampur",
    "facility": "Srirampur",
    "address": "Aknush Rustum Jadhav , Patil Spoken Classes ,Ward No.3 Opp . Damani Hospital , Shrirampur - 4130709",
    "officeType": "Leased",
    "centreType": "Training Room",
    "lessor": "Aknush Rustum Jadhav",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2026-04-01",
    "leaseEnd": "2027-03-31",
    "city": "srirampur"
  },
  {
    "sr": 50,
    "region": "West",
    "state": "Maharashtra",
    "location": "Nasik",
    "facility": "Nasik",
    "address": "Flat No 211, Rajan Complex, Datta Mandir Signal, Nashi-Puna Road, Above Vodafone Gallary, Nasik Road, Nasik-422101",
    "officeType": "Leased",
    "centreType": "Collection Centre",
    "lessor": "Nisha Nilesh Lalwani",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2024-02-01",
    "leaseEnd": "2027-01-31",
    "city": "nasik"
  },
  {
    "sr": 51,
    "region": "West",
    "state": "Gujarat",
    "location": "Baroda",
    "facility": "Baroda",
    "address": "Office No. 118, 1st Floor, Siddharth complex, R C Dutt Road, Alkapuri, Vadodara 390005",
    "officeType": "Leased",
    "centreType": "Collection Centre",
    "lessor": "Amish Haribhai Patel/Haribhai B Patel",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2024-02-14",
    "leaseEnd": "2027-02-13",
    "city": "baroda"
  },
  {
    "sr": 52,
    "region": "West",
    "state": "Gujarat",
    "location": "Ahmedabad",
    "facility": "Ahmedabad",
    "address": "BSQUARE Office Solutions , 6th Floor,57,58,59 Shree Krishna Center,Above Crossword,Nr. Mithakali Six Roads,Navrangpura,Ahmedabad-380009",
    "officeType": "Leased",
    "centreType": "Collection Centre",
    "lessor": "Bsquare office Solutions",
    "lessee": "Digitide Solutions Ltd.",
    "leaseStart": "2024-07-01",
    "leaseEnd": "2027-06-30",
    "city": "ahmedabad"
  },
  {
    "sr": 53,
    "region": "Central",
    "state": "Madhya Pradesh",
    "location": "Indore -1",
    "facility": "Brilliant Sapphire",
    "address": "Plot No.10, Scheme Number 78, Part II, Vijay Nagar, Indore, Madhya Pradesh 452010",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "Brilliant Estates Limited",
    "lessee": "Digitide Solutions Ltd",
    "leaseStart": "2026-09-01",
    "leaseEnd": "2029-08-31",
    "city": "indore"
  },
  {
    "sr": 54,
    "region": "Central",
    "state": "Madhya Pradesh",
    "location": "Indore -2",
    "facility": "MA Business center",
    "address": "4th Floor, MA Business center, Near Princess Sky Park, Vijay Nagar, Indore - 452011",
    "officeType": "Leased and Managed by Partner",
    "centreType": "Call Centre",
    "lessor": "Workie Pvt Ltd",
    "lessee": "Digitide Solutions Ltd",
    "leaseStart": "2025-04-01",
    "leaseEnd": "2028-03-31",
    "city": "indore"
  },
  {
    "sr": 55,
    "region": "Central",
    "state": "Madhya Pradesh",
    "location": "Chhindwara",
    "facility": "Ambara",
    "address": "Ambara Village, Parasia tehsil, Chhindwara District, Madhya Pradesh- 480449",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Call Centre",
    "lessor": "Bharti Uekey",
    "lessee": "Digitide Solutions Ltd",
    "leaseStart": "2026-02-01",
    "leaseEnd": "2028-01-31",
    "city": "chhindwara"
  },
  {
    "sr": 56,
    "region": "Central",
    "state": "Chhattisgarh",
    "location": "Raipur",
    "facility": "Chawla Complex",
    "address": "Chawla Complex, Ward Sai Nagar, Devendra Nagar Road, Raipur, Chhattisgarh-492001",
    "officeType": "Leased & Managed by Digitide",
    "centreType": "Collection Centre",
    "lessor": "ME N MOM",
    "lessee": "Digitide Solutions Ltd",
    "leaseStart": "2025-12-11",
    "leaseEnd": "2026-11-20",
    "city": "raipur"
  }
];
