/* Per-facility coordinates, keyed by tracker Sr number.
   Researched from public sources, one building at a time; direct geocoding
   APIs are not reachable from the build environment. Facilities sharing a
   building share its coordinate, which is why several Sr numbers repeat one
   point: that is the Ranigunj stack, the Coimbatore floors and so on.

   precision  building | street | locality | city, and the UI prints it on
              every facility card, so a coarse pin is never passed off as an
              exact one.
   confidence verified only where two independent sources agreed or one
              authoritative source resolved it.

   Nothing here is placed by eye. Coordinates outside the India bounding box
   are dropped by scripts/build_geo rather than corrected by hand, and those
   facilities fall back to the city centroid.
   Regenerate rather than hand-editing. */
window.DG_GEO = {
  13: {"lat":17.431548,"lng":78.488787,"precision":"building","confidence":"unconfirmed","source":"Mappls POI 'Lala Landmark, MG Road, Ranigunj, Secunderabad 500003'","building":"Ranigunj","notes":"Single map source; corroborated by door-number sequence of neighbouring MG Road POIs."},
  14: {"lat":17.431548,"lng":78.488787,"precision":"building","confidence":"unconfirmed","source":"Mappls POI 'Lala Landmark, MG Road, Ranigunj, Secunderabad 500003'","building":"Ranigunj","notes":"Single map source; corroborated by door-number sequence of neighbouring MG Road POIs."},
  15: {"lat":17.431548,"lng":78.488787,"precision":"building","confidence":"unconfirmed","source":"Mappls POI 'Lala Landmark, MG Road, Ranigunj, Secunderabad 500003'","building":"Ranigunj","notes":"Single map source; corroborated by door-number sequence of neighbouring MG Road POIs."},
  16: {"lat":17.431548,"lng":78.488787,"precision":"building","confidence":"unconfirmed","source":"Mappls POI 'Lala Landmark, MG Road, Ranigunj, Secunderabad 500003'","building":"Ranigunj","notes":"Single map source; corroborated by door-number sequence of neighbouring MG Road POIs."},
  17: {"lat":17.431548,"lng":78.488787,"precision":"building","confidence":"unconfirmed","source":"Mappls POI 'Lala Landmark, MG Road, Ranigunj, Secunderabad 500003'","building":"Ranigunj","notes":"Single map source; corroborated by door-number sequence of neighbouring MG Road POIs."},
  18: {"lat":17.44235,"lng":78.47548,"precision":"building","confidence":"verified","source":"Passport Seva Kendra at Gowra Trinity listing + Mappls Gowra Trinity POIs, agreeing within ~30 m","building":"Begumpet","notes":"Tracker pin code 500049 is wrong for this address; Gowra Trinity is 500003 (some tenants use 500016). 500049 is Gopanpally, far west Hyderabad."},
  19: {"lat":10.0889,"lng":77.0595,"precision":"city","confidence":"unconfirmed","source":"Munnar town centre, standard gazetteer value","building":"Munnar","notes":"Sara Cottage / building 1758A/IX has no web, map or directory footprint. Town-level only, deliberately not a building fix."},
  20: {"lat":11.010134,"lng":76.989233,"precision":"building","confidence":"unconfirmed","source":"Mappls POI 'Manchester Square, Pankaja Mill Road, Lakshmi Mills, Coimbatore 641037'","building":"Coimbatore","notes":"Cross-checked via company filings at 'No 14, Puliakulam Road'. Tracker pin 641038 appears to be a typo for 641037."},
  21: {"lat":11.010134,"lng":76.989233,"precision":"building","confidence":"unconfirmed","source":"Mappls POI 'Manchester Square, Pankaja Mill Road, Lakshmi Mills, Coimbatore 641037'","building":"Coimbatore","notes":"Cross-checked via company filings at 'No 14, Puliakulam Road'. Tracker pin 641038 appears to be a typo for 641037."},
  22: {"lat":11.010134,"lng":76.989233,"precision":"building","confidence":"unconfirmed","source":"Mappls POI 'Manchester Square, Pankaja Mill Road, Lakshmi Mills, Coimbatore 641037'","building":"Coimbatore","notes":"Cross-checked via company filings at 'No 14, Puliakulam Road'. Tracker pin 641038 appears to be a typo for 641037."},
  23: {"lat":12.930475,"lng":80.207769,"precision":"locality","confidence":"unconfirmed","source":"Pallikaranai 600100 neighbourhood centroid","building":"RVI Tower","notes":"RVI Towers confirmed to exist at No.149 Velachery-Tambaram Main Rd, 7 floors, but no published coordinate found. Not interpolated onto the road. One Google Maps lookup would settle it."},
  24: {"lat":12.930475,"lng":80.207769,"precision":"locality","confidence":"unconfirmed","source":"Pallikaranai 600100 neighbourhood centroid","building":"RVI Tower","notes":"RVI Towers confirmed to exist at No.149 Velachery-Tambaram Main Rd, 7 floors, but no published coordinate found. Not interpolated onto the road. One Google Maps lookup would settle it."},
  25: {"lat":12.919407,"lng":77.615218,"precision":"locality","confidence":"unconfirmed","source":"Mappls verified point inside Jai Bheem Nagar, BTM Layout Stage 1, 560068","building":"SS Plaza","notes":"SJR SS Plaza address confirmed (74/2, 27th Main, Old Madiwala) but no published coordinate. Locality point, not the building."},
  26: {"lat":22.79887,"lng":86.172312,"precision":"street","confidence":"unconfirmed","source":"Mappls POI 'Kadma Police Station, Stocking Road, Kadma, Jamshedpur 831005'","building":"Jamshedpur","notes":"Address says opposite the police station, so this is the correct road position but across the road from the building."},
  27: {"lat":22.579956,"lng":88.43795,"precision":"building","confidence":"verified","source":"latlong.net 'Technopolis, Salt Lake' + Mappls anchor opposite Technopolis, agreeing within ~25 m","building":"Technopolis","notes":"Technopolis IT Park, BP-4, Street No.1, BP Block, Sector V. Tracker address and pin correct."},
  28: {"lat":22.577023,"lng":88.431083,"precision":"building","confidence":"unconfirmed","source":"Mappls POI 'Tower 2, Millennium City IT Park, Block DN, Sector 5, Bidhan Nagar 700091'","building":"Millennium City","notes":"Specifically Tower 2 as the tracker asks, not the complex centroid. Sits ~800 m WSW of Technopolis, correct relative geometry."},
  29: {"lat":20.291424,"lng":85.856243,"precision":"building","confidence":"unconfirmed","source":"Mappls POI 'Esplanade Mall Rasulgarh, Bhubaneswar 751010'","building":"Bhubaneswar","notes":"Now Nexus Esplanade, Puri-Cuttack Road. Single underlying source, so not called verified."},
  30: {"lat":25.608817,"lng":85.139757,"precision":"street","confidence":"unconfirmed","source":"Mappls POI 'Safari, Geetanjali Palace, Jamal Road, Patna 800001'","building":"Patna","notes":"Jagtarni Tower exists on Jamal Road per company filings but has no published coordinate. Point on Jamal Road, not the building. Tracker address gives two building names, which is itself odd."},
  31: {"lat":26.185711,"lng":91.758367,"precision":"street","confidence":"unconfirmed","source":"Mappls POI 'Guwahati Club, GNB Road, Chenikuthi, Guwahati 781003', the landmark named in the address","building":"Guwahati","notes":"Kalpana Market is listed on GNB Road but carries no published coordinate. Bracketed by verified GNB Road POIs within ~100 m."},
  32: {"lat":19.1699,"lng":73.0021,"precision":"building","confidence":"verified","source":"Three Mappls POIs inside Reliable Tech Park agreeing within ~100 m; one DIGIPIN-backed","building":"Airoli 1","notes":"Cloud City campus, Gut No. 31, Thane-Belapur Road. Centroid lands on the park structure."},
  33: {"lat":19.1699,"lng":73.0021,"precision":"building","confidence":"verified","source":"Three Mappls POIs inside Reliable Tech Park agreeing within ~100 m; one DIGIPIN-backed","building":"Airoli 1","notes":"Cloud City campus, Gut No. 31, Thane-Belapur Road. Centroid lands on the park structure."},
  34: {"lat":19.171324,"lng":73.001303,"precision":"building","confidence":"verified","source":"Mappls 'RBL Bank ATM, Empire Tower, Airoli 400708', DIGIPIN 4FK-72M-FKPC re-encoded exactly","building":"Airoli 4","notes":"Tracker says 'Plot No. K-10, MIDC, TTC Ind. Area'; officefreedom, coworkingcafe and ZaubaCorp all give 'Cloud City Campus, Gut No. 31, Village Ilthen'. No source supports K-10. 179 m from Reliable Tech Park, consistent w"},
  35: {"lat":19.142437,"lng":73.012486,"precision":"building","confidence":"unconfirmed","source":"Mappls 'Skypal System, 802, Sigma IT Park, MIDC Sector 8, Rabale 400701'","building":"Sigma IT Park, Rabale","notes":"Only one public record names Sigma IT Park at a coordinate. Locality certain, exact plot not closed. Kanakia Sigma IT Park is plots R-203/204."},
  36: {"lat":19.142437,"lng":73.012486,"precision":"building","confidence":"unconfirmed","source":"Mappls 'Skypal System, 802, Sigma IT Park, MIDC Sector 8, Rabale 400701'","building":"Sigma IT Park, Rabale","notes":"Only one public record names Sigma IT Park at a coordinate. Locality certain, exact plot not closed. Kanakia Sigma IT Park is plots R-203/204."},
  37: {"lat":19.265978,"lng":72.965734,"precision":"building","confidence":"verified","source":"Mappls 'MBC Park, MBC Infotech Park, Near Hypercity Mall, Godbunder Road, Thane 400615', DIGIPIN 4FK-8MF-767M","building":"Kasar","notes":"Record name matches the tracker address almost verbatim including the Hypercity landmark."},
  38: {"lat":19.265978,"lng":72.965734,"precision":"building","confidence":"verified","source":"Mappls 'MBC Park, MBC Infotech Park, Near Hypercity Mall, Godbunder Road, Thane 400615', DIGIPIN 4FK-8MF-767M","building":"Kasar","notes":"Record name matches the tracker address almost verbatim including the Hypercity landmark."},
  39: {"lat":19.198343,"lng":72.953959,"precision":"building","confidence":"verified","source":"Four independent Mappls records within ~60 m; DIGIPIN 4FK-7J8-9242 and base64 coordinate agree to 5 dp","building":"Ashar IT Park","notes":"Strongest fix in the set. 'Jayshri Baug' and Road No. 16Z both match the tracker address."},
  40: {"lat":19.197535,"lng":72.956652,"precision":"building","confidence":"verified","source":"Mappls geocode of 'A-186, Road Number 16, Wagle Industrial Estate, Thane 400604'; identity from CBRE and Awfis giving Kalpataru Prime at A-186","building":"Kalpataru Prime","notes":"Plot-number duality: tracker says D-3, CBRE/Awfis/JLL say A-186, both carry 'Unit No. 2'. Two registry designations for one plot, not two buildings. 297 m from Ashar IT Park as expected."},
  41: {"lat":19.228028,"lng":72.858895,"precision":"street","confidence":"unconfirmed","source":"Mappls shop POI physically on Carter Road No. 2, Borivali East 400066; Shatabdi Municipal Hospital 223 m away matches the address landmark","building":"Borivali","notes":"'Om Shreeji Darshan' could not be located publicly. A same-name society on 99acres is in Nalasopara East and was deliberately not used. Address also says Dattapada, which runs further north-east, so the segment may be of"},
  42: {"lat":19.226599,"lng":72.979879,"precision":"building","confidence":"verified","source":"Two Mappls records for 'ETPL Tower, Kolshet Road, Thane West 400607' agreeing to ~11 m; DIGIPIN 4FK-7C9-P494 re-encoded exactly","building":"Kolshet","notes":"Tracker pin code 400604 is wrong. Kolshet/Dhokali is 400607; 400604 is Wagle Estate about 3 km south-west."},
  43: {"lat":18.615004,"lng":73.813776,"precision":"building","confidence":"verified","source":"Five Mappls records inside ICC Devi Gaurav Tech Park within ~80 m; DIGIPIN 4FP-334-3T59 re-encoded exactly","building":"Devi IT","notes":"Mappls records 'Site No 191 to 192, Old Bombay Pune Road', matching the tracker's Sr.No. 191 to 195. This is the one owned site in the portfolio."},
  44: {"lat":18.547648,"lng":73.941082,"precision":"building","confidence":"unconfirmed","source":"Mappls POI naming 'E Park, Thite Nagar, Kharadi 411014'; JLL confirms E Park North and South Towers at Plot No 3/1 MIDC","building":"Kharadi E Park","notes":"Only one Mappls POI names E Park with a coordinate. Could not confirm which of the two towers."},
  45: {"lat":18.551516,"lng":73.937857,"precision":"building","confidence":"verified","source":"Three Mappls records within ~40 m, two DIGIPIN-backed, including a 7th-floor tenant inside Almonte IT Park","building":"Almonte","notes":"Full name Vascon Almonte IT Park, Rakshak Nagar, Kharadi, matching the tracker address."},
  46: {"lat":22.405238,"lng":69.010155,"precision":"locality","confidence":"verified","source":"industryabout.com Tata Chemicals Mithapur soda ash plant; second database gem.wiki gives the cement plant 1.1 km away","building":"Mithapur","notes":"Deliberately locality. The works plus township spans about 2 km and nothing identifies which building holds the office. Administrative note: Mithapur is in Devbhumi Dwarka district since 2013, so the tracker's 'District "},
  47: {"lat":21.139929,"lng":79.05601,"precision":"street","confidence":"unconfirmed","source":"Mappls 'Ramnagar Bus Stop, Cement Road, Dharmapeth Extension, Nagpur 440010', corroborated by a second Cement Road POI 65 m away","building":"Nagpur","notes":"No map provider indexes R.K. Business Centre itself. Point is on Cement Road; building plausibly within ~200 m."},
  48: {"lat":16.694216,"lng":74.217697,"precision":"street","confidence":"unconfirmed","source":"Mappls 'Life Insurance Corporation, Tarabai Road, Shivaji Peth, Kolhapur 416012'","building":"kolhapur","notes":"No Maha E-Seva Kendra on Tarabai Road is indexed, and house no. 1605 A-Ward is not mappable. Mid-segment point; along-road uncertainty about 250 m."},
  49: {"lat":19.618223,"lng":74.65305,"precision":"street","confidence":"unconfirmed","source":"Mappls 'Damani Hospital, Bazar Road, Shrirampur 413709', the landmark the address names","building":"Srirampur","notes":"Patil Spoken Classes is not indexed anywhere. Address defines itself as opposite the hospital, so true location should be within 30 to 50 m. Tracker pin '4130709' is a typo for 413709."},
  50: {"lat":19.956152,"lng":73.83415,"precision":"building","confidence":"verified","source":"Mappls tenant POI inside Rajan Complex, Datta Mandir Signal, Nashik Road 422101, plus a second record 35 m behind the same building","building":"Nasik","notes":"The POI's 'Beside Vodafone Store' landmark independently matches the tracker's 'Above Vodafone Gallary'."},
  51: {"lat":22.310246,"lng":73.169604,"precision":"building","confidence":"verified","source":"homes247 record for Siddharth Complex, Alkapuri, cross-checked against a Mappls bank POI opposite it on RC Dutt Road","building":"Baroda","notes":"Two independent sources within ~70 m. A third source 400 m east was treated as an outlier. Tracker pin 390005 looks wrong: RC Dutt Road / Alkapuri is 390007."},
  52: {"lat":23.032966,"lng":72.565456,"precision":"building","confidence":"unconfirmed","source":"Mappls ground-floor tenant POI of Shree Krishna Centre, Mithakali Six Roads, Navrangpura 380009","building":"Ahmedabad","notes":"Geometrically building-level but only one source. Mappls' own generic junction point sits 570 m south, an internal inconsistency in that provider; the named-building record was preferred."},
  53: {"lat":22.763322,"lng":75.884012,"precision":"building","confidence":"unconfirmed","source":"Mappls place record for 'Brilliant Sapphire, Scheme No 78, Vijay Nagar, Indore 452010', DIGIPIN 34P-LL4-JL4P","building":"Brilliant Sapphire","notes":"Exact name, scheme and pin match. Single provider, hence unconfirmed. Relative position against Vijay Nagar Square is right for Scheme 78 Part II."},
  54: {"lat":22.745815,"lng":75.893029,"precision":"street","confidence":"unconfirmed","source":"Mappls 'Princes Business Skypark, AB Road, LIG Colony, Indore 452011', the landmark the tracker names","building":"MA Business center","notes":"MA Business Centre is listed by CBRE at 'Unnamed Road', which is why no coordinate exists. Block bounded by three independent anchors; true building likely within ~200 m."},
  55: {"lat":22.196306,"lng":78.754807,"precision":"city","confidence":"unconfirmed","source":"Parasia town, the tehsil headquarters named in the address","building":"Ambara","notes":"Honest gap. Ambara village is not in Census 2011 listings, VillageInfo or any map provider. A similarly named 'Ambada' census town was deliberately NOT substituted. Pin 480449 is a genuine Parasia pocket but Parasia town"},
  56: {"lat":21.260515,"lng":81.642882,"precision":"street","confidence":"unconfirmed","source":"Mappls 'Heritage Hospital, Devendra Nagar, Raipur 492001'; Mappls separately describes Chawla Complex as opposite Heritage Hospital","building":"Chawla Complex","notes":"True location should be within ~60 m, across the road. Chawla Complex is independently attested by India Post and an HDFC branch addressed there. India Post assigns it 492009 against the tracker's 492001; both are Raipur"}
};
