-- ATLAS seed — generated from verified recon. Run AFTER 001_atlas_schema.sql.
-- Safe to re-run: every statement upserts.
begin;

-- metro stations (verified OSM railway=station nodes)
insert into metro_stations (id,line,name_en,lat,lng,source) values ('singayyanapalya','Purple Line','Singayyanapalya',12.9965445,77.6927176,'OSM railway=station, Overpass 2026-08-22') on conflict (id) do nothing;
insert into metro_stations (id,line,name_en,lat,lng,source) values ('garudacharpalya','Purple Line','Garudacharpalya',12.9934505,77.7036768,'OSM railway=station, Overpass 2026-08-22') on conflict (id) do nothing;
insert into metro_stations (id,line,name_en,lat,lng,source) values ('seetharampalya','Purple Line','Seetharampalya',12.9808558,77.7087854,'OSM railway=station, Overpass 2026-08-22') on conflict (id) do nothing;
insert into metro_stations (id,line,name_en,lat,lng,source) values ('hoodi','Purple Line','Hoodi',12.9888029,77.711326,'OSM railway=station, Overpass 2026-08-22') on conflict (id) do nothing;
insert into metro_stations (id,line,name_en,lat,lng,source) values ('kundalahalli','Purple Line','Kundalahalli',12.977594,77.7155586,'OSM railway=station, Overpass 2026-08-22') on conflict (id) do nothing;
insert into metro_stations (id,line,name_en,lat,lng,source) values ('nallurahalli','Purple Line','Nallurahalli',12.9766408,77.7248845,'OSM railway=station, Overpass 2026-08-22') on conflict (id) do nothing;
insert into metro_stations (id,line,name_en,lat,lng,source) values ('sri-sathya-sai-hospital','Purple Line','Sri Sathya Sai Hospital',12.9811949,77.7275361,'OSM railway=station, Overpass 2026-08-22') on conflict (id) do nothing;
insert into metro_stations (id,line,name_en,lat,lng,source) values ('pattandur-agrahara','Purple Line','Pattandur Agrahara',12.9876393,77.7377718,'OSM railway=station, Overpass 2026-08-22') on conflict (id) do nothing;
insert into metro_stations (id,line,name_en,lat,lng,source) values ('kadugodi-tree-park','Purple Line','Kadugodi Tree Park',12.9856503,77.7470121,'OSM railway=station, Overpass 2026-08-22') on conflict (id) do nothing;
insert into metro_stations (id,line,name_en,lat,lng,source) values ('hopefarm-channasandra','Purple Line','Hopefarm Channasandra',12.9873426,77.7538033,'OSM railway=station, Overpass 2026-08-22') on conflict (id) do nothing;
insert into metro_stations (id,line,name_en,lat,lng,source) values ('whitefield-kadugodi-','Purple Line','Whitefield (Kadugodi)',12.9957428,77.7579489,'OSM railway=station, Overpass 2026-08-22') on conflict (id) do nothing;

-- properties
insert into properties (id,client_slug,name,lat,lng,coord_confirmed,coord_source) values ('itpl','basilic-fly','ITPL — Explorer Block',12.9857085,77.7346595,true,'OSM footprint centroid') on conflict (id) do update set lat=excluded.lat,lng=excluded.lng,coord_confirmed=excluded.coord_confirmed,coord_source=excluded.coord_source;
insert into properties (id,client_slug,name,lat,lng,coord_confirmed,coord_source) values ('primeco','basilic-fly','Primeco Union City — Tower B',12.9890573,77.7326259,true,'OSM footprint centroid') on conflict (id) do update set lat=excluded.lat,lng=excluded.lng,coord_confirmed=excluded.coord_confirmed,coord_source=excluded.coord_source;
insert into properties (id,client_slug,name,lat,lng,coord_confirmed,coord_source) values ('sumadhura','basilic-fly','Sumadhura Capitol',12.9849593,77.7502982,true,'OSM footprint centroid') on conflict (id) do update set lat=excluded.lat,lng=excluded.lng,coord_confirmed=excluded.coord_confirmed,coord_source=excluded.coord_source;
insert into properties (id,client_slug,name,lat,lng,coord_confirmed,coord_source) values ('brigade','basilic-fly','Brigade Utopia Elysium',12.9340716,77.7443147,true,'OSM footprint centroid') on conflict (id) do update set lat=excluded.lat,lng=excluded.lng,coord_confirmed=excluded.coord_confirmed,coord_source=excluded.coord_source;
insert into properties (id,client_slug,name,lat,lng,coord_confirmed,coord_source) values ('starmark','basilic-fly','Starmark Camelot',12.9849722,77.7266886,true,'OSM footprint centroid') on conflict (id) do update set lat=excluded.lat,lng=excluded.lng,coord_confirmed=excluded.coord_confirmed,coord_source=excluded.coord_source;
insert into properties (id,client_slug,name,lat,lng,coord_confirmed,coord_source) values ('totalenv','basilic-fly','Total Environment',12.9912395,77.6897334,false,'OSM locality centroid — NOT the building') on conflict (id) do update set lat=excluded.lat,lng=excluded.lng,coord_confirmed=excluded.coord_confirmed,coord_source=excluded.coord_source;
insert into properties (id,client_slug,name,lat,lng,coord_confirmed,coord_source) values ('yliving','basilic-fly','Y Living',12.9696365,77.7497448,false,'OSM locality centroid — NOT the building') on conflict (id) do update set lat=excluded.lat,lng=excluded.lng,coord_confirmed=excluded.coord_confirmed,coord_source=excluded.coord_source;

-- property -> station links (drive=OSRM, walk=derived from road distance)
insert into property_station_links (property_id,station_id,is_nearest,walk_m,walk_min,drive_m,drive_min,method,source_url) values ('itpl','pattandur-agrahara',true,1913,24,1913,3,'osrm','https://router.project-osrm.org') on conflict (property_id,station_id) do update set walk_m=excluded.walk_m,walk_min=excluded.walk_min,drive_m=excluded.drive_m,drive_min=excluded.drive_min;
insert into property_station_links (property_id,station_id,is_nearest,walk_m,walk_min,drive_m,drive_min,method,source_url) values ('primeco','pattandur-agrahara',true,589,7,589,1,'osrm','https://router.project-osrm.org') on conflict (property_id,station_id) do update set walk_m=excluded.walk_m,walk_min=excluded.walk_min,drive_m=excluded.drive_m,drive_min=excluded.drive_min;
insert into property_station_links (property_id,station_id,is_nearest,walk_m,walk_min,drive_m,drive_min,method,source_url) values ('sumadhura','kadugodi-tree-park',true,402,5,402,1,'osrm','https://router.project-osrm.org') on conflict (property_id,station_id) do update set walk_m=excluded.walk_m,walk_min=excluded.walk_min,drive_m=excluded.drive_m,drive_min=excluded.drive_min;
insert into property_station_links (property_id,station_id,is_nearest,walk_m,walk_min,drive_m,drive_min,method,source_url) values ('brigade','nallurahalli',true,7577,95,7577,10,'osrm','https://router.project-osrm.org') on conflict (property_id,station_id) do update set walk_m=excluded.walk_m,walk_min=excluded.walk_min,drive_m=excluded.drive_m,drive_min=excluded.drive_min;
insert into property_station_links (property_id,station_id,is_nearest,walk_m,walk_min,drive_m,drive_min,method,source_url) values ('starmark','sri-sathya-sai-hospital',true,1116,14,1116,2,'osrm','https://router.project-osrm.org') on conflict (property_id,station_id) do update set walk_m=excluded.walk_m,walk_min=excluded.walk_min,drive_m=excluded.drive_m,drive_min=excluded.drive_min;
insert into property_station_links (property_id,station_id,is_nearest,walk_m,walk_min,drive_m,drive_min,method,source_url) values ('totalenv','singayyanapalya',true,1391,17,1391,2,'osrm','https://router.project-osrm.org') on conflict (property_id,station_id) do update set walk_m=excluded.walk_m,walk_min=excluded.walk_min,drive_m=excluded.drive_m,drive_min=excluded.drive_min;
insert into property_station_links (property_id,station_id,is_nearest,walk_m,walk_min,drive_m,drive_min,method,source_url) values ('yliving','kadugodi-tree-park',true,2213,28,2213,3,'osrm','https://router.project-osrm.org') on conflict (property_id,station_id) do update set walk_m=excluded.walk_m,walk_min=excluded.walk_min,drive_m=excluded.drive_m,drive_min=excluded.drive_min;

-- competitors (every row carries a citation; schema enforces source_url NOT NULL)
insert into property_competitors (property_id,name,category,lat,lng,distance_m,source_url,source_name,confidence) values ('itpl','DNEG','VFX — feature film',12.9857365,77.7346869,4,'https://www.dneg.com/location/bengaluru','DNEG official site','verified');
insert into property_competitors (property_id,name,category,lat,lng,distance_m,source_url,source_name,confidence) values ('itpl','88 Pictures','Animation / VFX / games',12.9889029,77.7310416,529,'https://88.pictures/bangalore/','88 Pictures official site','unconfirmed');
insert into property_competitors (property_id,name,category,lat,lng,distance_m,source_url,source_name,confidence) values ('itpl','Astra Studios','VFX / animation / virtual production',12.9863725,77.739803,562,'https://theastrastudios.com/studio','Astra Studios official site','verified');
insert into property_competitors (property_id,name,category,lat,lng,distance_m,source_url,source_name,confidence) values ('itpl','DeMeg Studios','3D animation / VFX',12.9922533,77.7361863,746,'https://www.demegstudios.com/','DeMeg Studios official site','unconfirmed');
insert into property_competitors (property_id,name,category,lat,lng,distance_m,source_url,source_name,confidence) values ('primeco','88 Pictures','Animation / VFX / games',12.9889029,77.7310416,173,'https://88.pictures/bangalore/','88 Pictures official site','unconfirmed');
insert into property_competitors (property_id,name,category,lat,lng,distance_m,source_url,source_name,confidence) values ('primeco','DNEG','VFX — feature film',12.9857365,77.7346869,432,'https://www.dneg.com/location/bengaluru','DNEG official site','verified');
insert into property_competitors (property_id,name,category,lat,lng,distance_m,source_url,source_name,confidence) values ('primeco','DeMeg Studios','3D animation / VFX',12.9922533,77.7361863,525,'https://www.demegstudios.com/','DeMeg Studios official site','unconfirmed');
insert into property_competitors (property_id,name,category,lat,lng,distance_m,source_url,source_name,confidence) values ('primeco','Astra Studios','VFX / animation / virtual production',12.9863725,77.739803,833,'https://theastrastudios.com/studio','Astra Studios official site','verified');
insert into property_competitors (property_id,name,category,lat,lng,distance_m,source_url,source_name,confidence) values ('starmark','88 Pictures','Animation / VFX / games',12.9889029,77.7310416,643,'https://88.pictures/bangalore/','88 Pictures official site','unconfirmed');
insert into property_competitors (property_id,name,category,lat,lng,distance_m,source_url,source_name,confidence) values ('starmark','DNEG','VFX — feature film',12.9857365,77.7346869,871,'https://www.dneg.com/location/bengaluru','DNEG official site','verified');

-- media (storage_path is repo-relative until the Storage bucket exists)
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','photo','media/starmark/starmark-07-097f1831.jpg',1280,720,'landscape',0,'Exterior — corner elevation','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','photo','media/starmark/starmark-01-0880ce8d.jpg',1280,720,'landscape',1,'Lift lobby','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','photo','media/starmark/starmark-13-48ca28c4.jpg',1280,720,'landscape',2,'Meeting room','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','photo','media/starmark/starmark-14-a90d8f87.jpg',1280,720,'landscape',3,'Warm shell floor plate','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','photo','media/starmark/starmark-03-8b55e24b.jpg',1280,720,'landscape',4,'Basement parking','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','photo','media/starmark/starmark-18-7e5a8a30.jpg',720,1280,'portrait',5,'Basement parking — services','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','video','media/starmark/starmark-04-0e90cce1.mp4',NULL,NULL,NULL,6,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','video','media/starmark/starmark-06-a7a6b575.mp4',NULL,NULL,NULL,7,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','video','media/starmark/starmark-08-a574d7f9.mp4',NULL,NULL,NULL,8,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','video','media/starmark/starmark-09-ceeade13.mp4',NULL,NULL,NULL,9,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','video','media/starmark/starmark-10-2625456f.mp4',NULL,NULL,NULL,10,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','video','media/starmark/starmark-11-5d4c76e7.mp4',NULL,NULL,NULL,11,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','video','media/starmark/starmark-12-00039071.mp4',NULL,NULL,NULL,12,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','video','media/starmark/starmark-15-bd84b69e.mp4',NULL,NULL,NULL,13,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','video','media/starmark/starmark-16-0c24828c.mp4',NULL,NULL,NULL,14,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('starmark','video','media/starmark/starmark-17-5405cf7a.mp4',NULL,NULL,NULL,15,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('primeco','photo','media/primeco/primeco-04-a5673065.jpg',900,1600,'portrait',0,'Café & breakout','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('primeco','photo','media/primeco/primeco-06-e873ab28.jpg',1600,900,'landscape',1,'Basement parking — Level Q2','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('primeco','video','media/primeco/primeco-01-3b735711.mp4',NULL,NULL,NULL,2,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('primeco','video','media/primeco/primeco-02-d2cc8300.mp4',NULL,NULL,NULL,3,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('primeco','video','media/primeco/primeco-03-d3c6eb12.mp4',NULL,NULL,NULL,4,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('primeco','video','media/primeco/primeco-05-5ccddf8f.mp4',NULL,NULL,NULL,5,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('primeco','video','media/primeco/primeco-07-a0867ac4.mp4',NULL,NULL,NULL,6,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);
insert into property_media (property_id,kind,storage_path,width,height,orientation,sort_order,caption,source,confidence,confirmations) values ('sumadhura','video','media/sumadhura/sumadhura-01-60fc0744.mov',NULL,NULL,NULL,0,'Site video','Supplied by Autopilot Offices, origin unstated','unconfirmed',array['supplied-by-client']);

commit;
